# .gitpod.yml


tasks:
  # Install AWS CLI and configure
  - name: aws-cli-installation
    env:
      AWS_CLI_AUTO_PROMPT: on-partial  
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      rm -rf awscliv2.zip
      cd $THEIA_WORKSPACE_ROOT

      # Create AWS credentials and config directories
      mkdir -p ~/.aws

      # Set AWS credentials
      echo "[default]" > ~/.aws/credentials
      echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
      echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials

      # Set AWS region and output format
      echo "[default]" > ~/.aws/config
      echo "region=$AWS_REGION" >> ~/.aws/config
      echo "output=json" >> ~/.aws/config

      # Set permissions for the credentials and config files
      chmod 600 ~/.aws/credentials ~/.aws/config


  # Install utilities like `tree`
  - name: utils
    before: |
      sudo apt-get install tree


  - name: AWS SDK Python
    command: | 
      pip install boto3

  - name: Terraform  # install terraform
    before: |
      sudo apt-get update && sudo apt-get install -y gnupg software-properties-common 
      wget -O- https://apt.releases.hashicorp.com/gpg | \
      gpg --dearmor | \
      sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
      gpg --no-default-keyring \
      --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg \
      --fingerprint
      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
      https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
      sudo tee /etc/apt/sources.list.d/hashicorp.list
      sudo apt update
      sudo apt-get install terraform



    
