# .gitpod.yml


tasks:
  # Install AWS CLI and configure
  - name: aws-cli-installation
    env:
      AWS_CLI_AUTO_PROMPT: on-partial  
    before: |
      ./bin/install_aws_cli.sh

  # Install utilities like `tree`
  - name: utils
    before: |
      sudo apt-get install tree


  - name: AWS SDK Python
    command: | 
      pip install boto3

  - name: Terraform  # install terraform
    before: |
      ./bin/install_terraform.sh

  - name: cdk
    before: |
       npm install -g aws-cdk



    
