#!/usr/bin/env bash
echo "== put object"

set -e 

if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-buckaer-name"
    exit 1
fi

if [ -z "$2" ]; then
    echo "There should be a filename. eg. ./bucket my-bucket-name my-filename "
    exit 1
fi




BUCKET_NAME=$1
ABSOLUTE_FILEPATH=$2


FILENAME=$(basename "$ABSOLUTE_FILEPATH")
echo $FILENAME

aws s3api put-object \
    --bucket $BUCKET_NAME \
    --body $ABSOLUTE_FILEPATH \
    --key $FILENAME