#!/usr/bin/env bash
echo "== sync"

set -e 

if [ -z "$1" ]; then
    echo "No bucket name is given"
    exit 1
fi

if [ -z "$2" ]; then
    echo "No file name is given"
    exit 1
fi

if [ -z "$3" ]; then
    echo "No file number is given"
    exit 1
fi


BUCKET_NAME=$1
FILENAME=$2
FILENUM=$3
# Generate a random number of files (between 5 and 15 files)
num_files=$((RANDOM % 11 + 5))

OUTPUT_DIR="/tmp/s3-bash-scripts"
#rm -r $OUTPUT_DIR

mkdir -p $OUTPUT_DIR



# Create the files and add random data to each
for i in $(seq 1 $num_files)
do
    filename="$OUTPUT_DIR/${FILENAME}${FILENUM}_$i.txt"
    # Generate a random string of random length between 5 and 20 characters
    random_data=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w $((RANDOM % 16 + 5)) | head -n 1)
    echo "$random_data" > "$filename"
    echo "Created $filename with random data."
done

echo "$num_files files created with random data."
tree $OUTPUT_DIR


aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files