AWSTemplateFormatVersion: 2010-09-09
Description: S3 Bucket
Parameters:
  BucketName:
    Type: String
    Default: sarvaawsbucket7
    Description: BucketName for S3
Resources:
  S3Bucket:
  #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html
    Type: 'AWS::S3::Bucket'
    DeletionPolicy:  Retain
    Properties:
      BucketName: !Ref BucketName

